### ISSUE TITLE
Docker images for concourse pipelines

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry/runtime-ci#5]
Based on @Amit-PivotalLabs 's email,  the **runtime-ci** Docker image is going to be unsupported soon. 

We currently are using it couple of our pipelines to create a final release. 

What are the recommendations for building clean and small Docker images moving forward? Will there be any new Docker images that will be supported that we can just replace for the task of `creating a bosh release`

**Comment by APShirley** [comment]
Hi Tushar,

Our suggested best practice moving forward is for teams to maintain their own docker images for their pipelines. The reason for this is that our pipelines change rapidly and as a result the images we are using will also change, and we do not intend to maintain backward compatible Docker images as they get bloated easily and are hard to maintain without breaking changes. 

If you choose to build your own images we also  suggest you keep only what you need in these images, as it also becomes difficult to regain context as to the reasons why pieces of software were added in the past which can lead to confusion about whether they are even needed in the image.  

Our solution for this is to use concourse to automate the building and pushing of images to Dockerhub. You can see an example of our Docker image pipeline [here](https://github.com/cloudfoundry/runtime-ci/blob/master/pipelines/build-docker-images.yml).  The nice thing about a pipeline like this is that image maintenance becomes exceedingly easy since all you need to do is find and replace software that you want to upgrade/change in all your relevant Dockerfiles and trigger the builds off of changes to each Dockerfile to do the rest. Hence all it takes is a `git push` and you end up with shiny new Docker images.

We have a single image for each task in our pipelines, to which we add new software only when needed. There is a good example of a Docker image to use for the `create-release` task in the same directory as our [`create-release` pipeline task](https://github.com/cloudfoundry/runtime-ci/blob/master/scripts/ci/create-release/Dockerfile). You should be able to copy that Dockerfile and build and customize your own image, which you can push to your own repo and have the freedom to modify it at will. 

Let me know if you have anymore questions.

Cheers,
Alvaro

**Comment by robdimsdale** [comment]
@tushar-dadlani we'll close this issue now, as there's been no response in a week. Please reach out to us if you have any further questions or encounter any issues.

Thanks,
Rob

**Comment by tushar-dadlani** [comment]
Thanks for addressing with a detailed explanation by @APShirley.
